### ISSUE TITLE
Suchfunktion bei Import

### ISSUE THREAD

**Issue by carlaterboven** [hpi-swa-teaching/SWT18-Project-02#8]
Beim Importieren von Schriftarten aus dem Internet hätte ich gerne eine Suchfunktion, um 
schnell eine von mir gewünschte Schrift zu finden.

**Comment by ekrebs5** [comment]
Ich hätte gern im FontImportertool ein Textfeld und einen Button, mit dem ich bei Google Webfonts nach Fonts entsprechend meines eingegebenen Textes suchen kann.
Die ersten 10 Ergebnisse sollen dann als Text angezeigt werden. (Bei einer neuen Suche wird der alte Text gelöscht)

**Comment by ekrebs5** [comment]
abgenommen
